spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/my-pro?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: toot
    password: root2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: admin2019
    # 连接超时时间（毫秒）
    timeout: 3000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000ms
        # 连接池中的最大空闲连接（负数没有限制）
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  # mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-pro
