# 服务名： frame-demo.service
server:
  port: 8080

spring:
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: org.ylc.frame.springboot.biz.*.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

# 监控信息
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, loggers, threaddump, heapdump, metrics
  endpoint:
    health:
      show-details: always
      show-components: always